baseURL = "/"
languageCode = "en-us"
title = "Wavelength"
theme = "kube"
description = "Wavelength is a site where you get to share your take and hear others"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Demo Pages"
    weight = -100
    url = "/docs/"
